version: '3.8'

services:
  pasienky-app:
    build: .
    container_name: pasienky-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./downloads:/data/downloads
      - ./logs:/data/logs 