services:
  pasienky-app:
    build: 
      context: ../../
      dockerfile: docs/dev-pasienky/Dockerfile
    container_name: pasienky-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PUPPETEER_PRODUCT=firefox
    restart: unless-stopped
    volumes:
      - ./downloads:/data/downloads
      - ./logs:/data/logs 
    security_opt:
      - seccomp=unconfined
    networks:
      - net0    

networks:
  net0:
    #    docker network create --driver overlay --attachable --subnet=192.168.70.0/24 net0
    #external: true
    name: net0